version: '3'

services:
  redis:
    image: redis
  worker:
    build: 
       context: .
       dockerfile: ./tensorflow_worker/Dockerfile
    volumes:
      - .:/code
      - ${TF_MODELS_PATH:-./models}:/models
    command: python manage.py start_worker BertCCAMClassifier /models
    depends_on:
      - redis
  severity_worker:
    build: 
       context: .
       dockerfile: ./tensorflow_worker/Dockerfile
    volumes:
      - .:/code
      - ${TF_MODELS_PATH:-./models}:/models
    command: python manage.py start_worker CRHSeverityClassifier /models/dummy_crh_severity_model --queue severity_queue
    depends_on:
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "${DJANGO_API_PORT:-8000}:8000"
    depends_on:
      - redis