version: '3'

services:
  db:
    image: postgres
  redis:
    image: redis
  worker:
    build: 
       context: .
       dockerfile: ./tensorflow_worker/Dockerfile
    volumes:
      - .:/code
    command: python manage.py surgery_classification_worker dummy_model
    environment:
      - GITHUB_USER
      - GITHUB_PASSWORD
    depends_on:
      - redis
  web:
    build: .
    #command: gunicorn -w 4 --threads 8 --worker-class=gthread --worker-tmp-dir /dev/shm predict_api.wsgi --bind :8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
