version: '3'

services:
  integration_tests:
    build: .
    command: python manage.py test --tag=integration
    volumes:
      - .:/code
    depends_on:
      - web
      - worker
      - severity_worker
