# Generated by Django 2.2.10 on 2020-03-10 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=80, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=10)),
                ('label_string', models.CharField(max_length=255, null=True)),
                ('error_message', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
